name: wvwa-generate-graphs

# Controls when the action will run.
on:
  workflow_dispatch

jobs: 
  generate-graphs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: flareforecast/flare:22.12.b6

    # Load repo and install R
    steps:
      - name: Checkout with wvwa-generate-graphs branch
        uses: actions/checkout@v2
        with:
          ref: wvwa-generate-graphs
          fetch-depth: 1

      - name: Set Up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: |
          R -e 'install.packages("lubridate")'
      - name: Run R Script
        run: /usr/local/bin/r wvwa-generate-graphs.R
      
      # Commit files ,and push
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add WeirDataFigures_$(date '+%Y-%m-%d').pdf MetDataFigures_$(date '+%Y-%m-%d').pdf BVRDataFigures_$(date '+%Y-%m-%d').pdf \
          FCRCatwalkDataFigures_$(date '+%Y-%m-%d').pdf CCRMetDataFigures_$(date '+%Y-%m-%d').pdf CCRWaterQualityDataFigures_$(date '+%Y-%m-%d').pdf
          git commit -m "wvwa-generate-graphs-$(date '+%Y-%m-%d')"
          git branch wvwa-graphs
          git push --force origin wvwa-graphs
